---
# default openstack libcloud schema

type: map
allowempty: True
mapping:
  image:
    required: True
    type: str
  flavor:
    required: True
    type: str
  networks:
    required: True
    type: seq
    sequence:
      - type: str
  floating_ip_pool:
    required: False
    type: str
  keypair:
    required: False
    type: str
  server_metadata:
    required: False
    type: map
    allowempty: True
    mapping:
      regex;(.*):
        required: False
        type: any
  credential:
    required: False
    type: map
    mapping:
      auth_url:
        type: str
        required: True
      username:
        type: str
        required: True
      password:
        type: str
        required: True
      tenant_name:
        type: str
        required: True
      domain_name:
        type: str
        required: False
      region:
        type: str
        required: False
      project_id:
        type: str
        required: False
      project_domain_id:
        type: str
        required: False
