
name: "Autobump tag on master branch and relese to pypi"

on:
  push:
    branches:
      - master
    paths:
      - 'teflo/__init__.py'

jobs:
  tag-new-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: salsify/action-detect-and-tag-new-version@v1
        with:
          version-command: |
            grep -o "'.*'" ./teflo/__init__.py | sed "s/'//g" | head -n 1
