# This is a basic workflow to help you get started with Actions

name: PR_unit_tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  pull_request:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container:
        - 'quay.io/centos/centos:stream9'
        - 'quay.io/centos/centos:stream'
        - 'quay.io/shshevac/teflo_ubi8'
      fail-fast: false

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - run: cat /etc/os-release

      - run: whoami
      - name: install utils
        run: dnf install -y util-linux
      - name: add user
        run: adduser teflouser

      - name: change user
        run: su - teflouser

      - name: check user
        run: whoami

      - name: add git files
        run: |
          echo ${{ secrets.DNO_SSH_PK }}
          mkdir ~/.ssh
          chmod 700 ~/.ssh
          echo ${{ secrets.DNO_SSH_PK }} >> ~/.ssh/test_key
          echo "" >> ~/.ssh/test_key
          chmod 600 ~/.ssh/test_key
#         eval `ssh-agent -s`
#         ssh-add ~/.ssh/test_key

      # Runs a single command using the runners shell
      - name: install required packages
        run: |
          dnf install -y glibc-langpack-en gcc python3 python3-devel python3-pip krb5-workstation krb5-devel git

      - name: check user
        run: whoami

#      - name: update locale
#        run: localectl set-locale LANG=en_US.utf8

      - name: install pip virtualenv and tox
        env:
          LANG: en_US.UTF-8
          LC_ALL: en_US.UTF-8
        run: |
          pip3 install virtualenv tox

      # Runs a set of commands using the runners shell
      - name: Run functional unit tests
        env:
          LANG: en_US.UTF-8
          LC_ALL: en_US.UTF-8
        run: tox -e py3-unit

      # Runs a set of commands using the runners shell
      - name: Run local scenario unit test
        env:
          LANG: en_US.UTF-8
          LC_ALL: en_US.UTF-8
        run: tox -e py3-scenario
